# @package _group_
debug: False
seed: 1
num_gpu: 2

save_root: '/home/kevin/Projects/oct_sc_segmentation/experiments_5'
experiment: 'experiment'
description:

start_fold:
load_checkpoint:
start_epoch: 1
num_epochs: 200
batch_size: 2
num_workers: 0
use_scheduler: True
data_parallel: False
tensorboard: True
device: 'cuda:0'
input_features:
  - 'image'
  - 'speckled_var'
